POST http://localhost:8080/user/register
Content-Type: application/json

{
  "surname":"Bazhenov",
  "name":"Nikita",
  "age":24,
  "login":"nikel-90",
  "password": "12345"
}

<> 2020-10-08T063345.200.json
<> 2020-10-08T063326.500.json
<> 2020-10-08T063134.500.json

###

GET http://localhost:8080/user


###

GET http://localhost:8080/user/1


###

POST http://localhost:8080/account/register
Content-Type: application/json

{
  "accountNumber":40165764,
    "userId":1
}



###
POST http://localhost:8080/card/register
Content-Type: application/json

{
  "cardNumber":401165764,
  "cardBalance":1122,
  "accountId": 1
}

###
GET /card/balance/1


###
GET /card/balance/add/1, 400

###

POST http://localhost:8080/card/balance/add
Content-Type: application/json

{
  "cardId": 1,
  "amount":1122
}