CREATE TABLE USER
(ID INTEGER NOT NULL,
SURNAME VARCHAR(255),
NAME VARCHAR(255),
AGE INTEGER,
PRIMARY KEY( ID ));

CREATE TABLE ACCOUNT
(ID INTEGER NOT NULL,
ACCOUNT_NUMBER INTEGER,
ID_USER INTEGER unique, --?unique
PRIMARY KEY( ID ));
--ALTER TABLE USER ADD FOREIGN KEY (ID) references ACCOUNT(ID_USER);
ALTER TABLE ACCOUNT ADD FOREIGN KEY (ID_USER) references USER(ID);

CREATE TABLE CARD
(ID INTEGER NOT NULL,
CARD_NUBMER INTEGER,
CARD_BAlANCE INTEGER,
ID_ACCOUNT INTEGER, --?unique
PRIMARY KEY( ID ),
FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID));
--ALTER TABLE ACCOUNT ADD FOREIGN KEY (ID) references CARD(ID_ACCOUNT);
ALTER TABLE CARD ADD FOREIGN KEY (ID_ACCOUNT) references ACCOUNT(ID);

