CREATE TABLE USER
(ID INTEGER NOT NULL,
SURNAME VARCHAR(255),
NAME VARCHAR(255),
AGE INTEGER,
PRIMARY KEY( ID ));

CREATE TABLE ACCOUNT
(ID INTEGER NOT NULL,
ACCOUNT_NUMBER INTEGER,
USER_ID INTEGER unique, --?unique
PRIMARY KEY( ID ));
ALTER TABLE ACCOUNT ADD FOREIGN KEY (USER_ID) references USER(ID);

CREATE TABLE CARD
(ID INTEGER NOT NULL,
CARD_NUBMER INTEGER,
CARD_BAlANCE INTEGER,
ACCOUNT_ID INTEGER, --?unique
PRIMARY KEY( ID ));
ALTER TABLE CARD ADD FOREIGN KEY (ACCOUNT_ID) references ACCOUNT(ID);

