CREATE TABLE USER
(ID INTEGER NOT NULL,
SURNAME VARCHAR(255),
NAME VARCHAR(255),
AGE INTEGER,
PRIMARY KEY( ID ));

CREATE TABLE ACCOUNT
(ID INTEGER NOT NULL,
ACCOUNT_NUMBER INTEGER,
ID_USER INTEGER,
PRIMARY KEY( ID ),
FOREIGN KEY (ID) REFERENCES USER(ID));

CREATE TABLE CARD
(ID INTEGER NOT NULL,
CARD_NUBMER INTEGER,
CARD_BAlANCE INTEGER,
ID_ACCOUNT INTEGER,
PRIMARY KEY( ID ),
FOREIGN KEY (ID) REFERENCES ACCOUNT(ID));

