CREATE TABLE USER
(ID IDENTITY NOT NULL PRIMARY KEY,
SURNAME VARCHAR(255),
NAME VARCHAR(255),
AGE INTEGER,
LOGIN VARCHAR(255),
PASSWORD VARCHAR(255));

CREATE TABLE ACCOUNT
(ID IDENTITY NOT NULL PRIMARY KEY,
ACCOUNT_NUMBER INTEGER,
USER_ID INTEGER NOT NULL unique);
ALTER TABLE ACCOUNT ADD FOREIGN KEY (USER_ID) references USER(ID);

CREATE TABLE CARD
(ID IDENTITY NOT NULL PRIMARY KEY,
CARD_NUMBER INTEGER,
CARD_BAlANCE INTEGER,
ACCOUNT_ID INTEGER NOT NULL );
ALTER TABLE CARD ADD FOREIGN KEY (ACCOUNT_ID) references ACCOUNT(ID);

